name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build & Strip (Static Linking=False;)
      run: |
        make all -j4 BUILD_TARGET=release
        strip ./chip-8

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: ./build/
        if-no-files-found: error

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: make all -j4 BUILD_TARGET=release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win-x86_64
          path: ./build
          if-no-files-found: error

  osx_x86_64:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install cmake
      run: |
        brew install cmake

    - name: Build
      run: make all -j4 BUILD_TARGET=release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx_executable
        path: ./build/
        if-no-files-found: error


