name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install x11 Devel Files
      run: |
        sudo apt-get update
        sudo apt-get install xorg xserver-xorg-core xserver-xorg libx11-dev

    - name: Build & Strip
      run: |
        make all -j4 BUILD_TARGET=release CC=gcc
        strip ./chip-8

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: ./chip-8
        if-no-files-found: error

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: make all -j4 BUILD_TARGET=release CC=gcc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win-x86_64
          path: chip-8.exe
          if-no-files-found: error

