name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install CMake (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install cmake xorg-dev

    - name: Install CMake (MacOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install cmake

    - name: Generate Builds Files (Linux or MacOS)
      if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
      run: |
        cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"

    - name: Generate Builds Files (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -T "ClangCL"

    - name: Build
      run: |
        cmake --build build/ --config=Release --parallel 4

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: ./build/
        if-no-files-found: error

